import { Game } from "@/types";

export const games: Game[] = [
  {
    code: "ByAWPfLYdJx",
    url: "https://peslsv.play.gamezop.com/g/ByAWPfLYdJx",
    name: {
      en: "Trap & Kill Virus",
    },
    isPortrait: true,
    description: {
      en: "Kill the virus by capturing areas of the screen. Beware, they multiply fast. Don’t go too close or you die.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/ByAWPfLYdJx/cover.jpg",
      brick: "https://static.gamezop.com/ByAWPfLYdJx/brick.png",
      thumb: "https://static.gamezop.com/ByAWPfLYdJx/thumb.png",
      wall: "https://static.gamezop.com/ByAWPfLYdJx/wall.png",
      square: "https://static.gamezop.com/ByAWPfLYdJx/square.png",
      screens: [
        "https://static.gamezop.com/ByAWPfLYdJx/game-1.png",
        "https://static.gamezop.com/ByAWPfLYdJx/game-2.png",
        "https://static.gamezop.com/ByAWPfLYdJx/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/ByAWPfLYdJx/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/ByAWPfLYdJx/brick-tiny.png",
    },
    categories: {
      en: ["Puzzle & Logic"],
    },
    tags: {
      en: ["Logic", "Family", "Girls", "Kids", "Level-based", "Puzzle"],
    },
    width: 375,
    height: 600,
    colorMuted: "#4c3c69",
    colorVibrant: "#871e3e",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 7870653,
    hasIntegratedAds: false,
  },
  {
    code: "HJ0eRFSWuV",
    url: "https://peslsv.play.gamezop.com/g/HJ0eRFSWuV",
    name: {
      en: "Where's Tom?",
    },
    isPortrait: false,
    description: {
      en: "Tom is missing and you have to lift up objects in a specific order to see if its hiding underneath.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/HJ0eRFSWuV/cover.jpg",
      brick: "https://static.gamezop.com/HJ0eRFSWuV/brick.png",
      thumb: "https://static.gamezop.com/HJ0eRFSWuV/thumb.png",
      wall: "https://static.gamezop.com/HJ0eRFSWuV/wall.png",
      square: "https://static.gamezop.com/HJ0eRFSWuV/square.png",
      screens: [
        "https://static.gamezop.com/HJ0eRFSWuV/game-1.png",
        "https://static.gamezop.com/HJ0eRFSWuV/game-2.png",
        "https://static.gamezop.com/HJ0eRFSWuV/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/HJ0eRFSWuV/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/HJ0eRFSWuV/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: [
        "Logic",
        "Educa-tional",
        "Endless",
        "Food",
        "Girls",
        "Kids",
        "Strategy",
        "Hidden Object",
        "Level-based",
        "Cute",
      ],
    },
    width: 800,
    height: 600,
    colorMuted: "#7c734c",
    colorVibrant: "#b8bd0d",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 773021,
    hasIntegratedAds: false,
  },
  {
    code: "B1MfIa4QCg",
    url: "https://peslsv.play.gamezop.com/g/B1MfIa4QCg",
    name: {
      en: "Spider Solitaire",
    },
    isPortrait: false,
    description: {
      en: "Get bitten by the solitaire bug and see if you can master this classic card game.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/B1MfIa4QCg/cover.jpg",
      brick: "https://static.gamezop.com/B1MfIa4QCg/brick.png",
      thumb: "https://static.gamezop.com/B1MfIa4QCg/thumb.png",
      wall: "https://static.gamezop.com/B1MfIa4QCg/wall.png",
      square: "https://static.gamezop.com/B1MfIa4QCg/square.png",
      screens: [
        "https://static.gamezop.com/B1MfIa4QCg/game-1.png",
        "https://static.gamezop.com/B1MfIa4QCg/game-2.png",
        "https://static.gamezop.com/B1MfIa4QCg/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/B1MfIa4QCg/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/B1MfIa4QCg/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: ["Boys", "Cards", "Classics", "Casino"],
    },
    width: 1600,
    height: 768,
    colorMuted: "#346749",
    colorVibrant: "#0c6c34",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 3408737,
    hasIntegratedAds: false,
  },
  {
    code: "SkKlAYSbuE",
    url: "https://peslsv.play.gamezop.com/g/SkKlAYSbuE",
    name: {
      en: "Snack Time",
    },
    isPortrait: false,
    description: {
      en: "It's snack time and there's only one rule: eat! Solve the puzzles to feed porky in this HTML5 game.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/SkKlAYSbuE/cover.jpg",
      brick: "https://static.gamezop.com/SkKlAYSbuE/brick.png",
      thumb: "https://static.gamezop.com/SkKlAYSbuE/thumb.png",
      wall: "https://static.gamezop.com/SkKlAYSbuE/wall.png",
      square: "https://static.gamezop.com/SkKlAYSbuE/square.png",
      screens: [
        "https://static.gamezop.com/SkKlAYSbuE/game-1.png",
        "https://static.gamezop.com/SkKlAYSbuE/game-2.png",
        "https://static.gamezop.com/SkKlAYSbuE/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/SkKlAYSbuE/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/SkKlAYSbuE/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: ["Logic", "Food", "Animal", "Strategy", "Level-based"],
    },
    width: 800,
    height: 600,
    colorMuted: "#645c38",
    colorVibrant: "#896104",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 386215,
    hasIntegratedAds: false,
  },
  {
    code: "rkHuVQ-1K",
    url: "https://peslsv.play.gamezop.com/g/rkHuVQ-1K",
    name: {
      en: "Illuminate",
    },
    isPortrait: true,
    description: {
      en: "Light up your brains and every room with a limited amount of lamps and reflectors in this puzzle game.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/rkHuVQ-1K/cover.jpg",
      brick: "https://static.gamezop.com/rkHuVQ-1K/brick.png",
      thumb: "https://static.gamezop.com/rkHuVQ-1K/thumb.png",
      wall: "https://static.gamezop.com/rkHuVQ-1K/wall.png",
      square: "https://static.gamezop.com/rkHuVQ-1K/square.png",
      screens: [
        "https://static.gamezop.com/rkHuVQ-1K/game-1.png",
        "https://static.gamezop.com/rkHuVQ-1K/game-2.png",
        "https://static.gamezop.com/rkHuVQ-1K/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/rkHuVQ-1K/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/rkHuVQ-1K/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: [
        "Logic",
        "Family",
        "Fun",
        "Strategy",
        "Pixel",
        "Level-based",
        "Puzzle",
      ],
    },
    width: 320,
    height: 480,
    colorMuted: "#744d34",
    colorVibrant: "#7c5434",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 328502,
    hasIntegratedAds: false,
  },
  {
    code: "HJKWbUj788l",
    url: "https://peslsv.play.gamezop.com/g/HJKWbUj788l",
    name: {
      en: "Clay Pigeon: Tap and Shoot",
    },
    isPortrait: false,
    description: {
      en: "Here's your chance to control a professional sniper and aim skeets in a shooting challenge.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/HJKWbUj788l/cover.jpg",
      brick: "https://static.gamezop.com/HJKWbUj788l/brick.png",
      thumb: "https://static.gamezop.com/HJKWbUj788l/thumb.png",
      wall: "https://static.gamezop.com/HJKWbUj788l/wall.png",
      square: "https://static.gamezop.com/HJKWbUj788l/square.png",
      screens: [
        "https://static.gamezop.com/HJKWbUj788l/game-1.png",
        "https://static.gamezop.com/HJKWbUj788l/game-2.png",
        "https://static.gamezop.com/HJKWbUj788l/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/HJKWbUj788l/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/HJKWbUj788l/brick-tiny.png",
    },
    categories: {
      en: ["Sports & Racing"],
    },
    tags: {
      en: ["3D", "Boys", "Shooting", "Physics", "Sports", "Difficult"],
    },
    width: 800,
    height: 480,
    colorMuted: "#3c4d32",
    colorVibrant: "#880c0a",
    privateAllowed: false,
    rating: 4.25,
    numberOfRatings: 2,
    gamePlays: 2399800,
    hasIntegratedAds: false,
  },
  {
    code: "HJeM-LsQI8x",
    url: "https://peslsv.play.gamezop.com/g/HJeM-LsQI8x",
    name: {
      en: "Cuby Zap",
    },
    isPortrait: false,
    description: {
      en: "Shoot the red cubes until your lives run out. But be careful: don't shoot the blue ones!",
    },
    gamePreviews: {
      en: "https://youtu.be/QFpU-v8MmCk",
    },
    assets: {
      cover: "https://static.gamezop.com/HJeM-LsQI8x/cover.jpg",
      brick: "https://static.gamezop.com/HJeM-LsQI8x/brick.png",
      thumb: "https://static.gamezop.com/HJeM-LsQI8x/thumb.png",
      wall: "https://static.gamezop.com/HJeM-LsQI8x/wall.png",
      square: "https://static.gamezop.com/HJeM-LsQI8x/square.png",
      screens: [
        "https://static.gamezop.com/HJeM-LsQI8x/game-1.png",
        "https://static.gamezop.com/HJeM-LsQI8x/game-2.png",
        "https://static.gamezop.com/HJeM-LsQI8x/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/HJeM-LsQI8x/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/HJeM-LsQI8x/brick-tiny.png",
    },
    categories: {
      en: ["Action"],
    },
    tags: {
      en: ["Arcade", "Shooter", "Fun", "Boys", "Minimal", "Endless"],
    },
    width: 800,
    height: 450,
    colorMuted: "#566777",
    colorVibrant: "#837d33",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 3978648,
    hasIntegratedAds: true,
  },
  {
    code: "H1WmafkP9JQ",
    url: "https://peslsv.play.gamezop.com/g/H1WmafkP9JQ",
    name: {
      en: "Tic Tac Toe",
    },
    isPortrait: true,
    description: {
      en: "Play the classic Tic Tac Toe online! Play in 3 difficulty modes or challenge thousands of other players online!",
    },
    gamePreviews: {
      en: "https://youtu.be/1RAmpf5qc54",
    },
    assets: {
      cover: "https://static.gamezop.com/H1WmafkP9JQ/cover.jpg",
      brick: "https://static.gamezop.com/H1WmafkP9JQ/brick.png",
      thumb: "https://static.gamezop.com/H1WmafkP9JQ/thumb.png",
      wall: "https://static.gamezop.com/H1WmafkP9JQ/wall.png",
      square: "https://static.gamezop.com/H1WmafkP9JQ/square.png",
      screens: [
        "https://static.gamezop.com/H1WmafkP9JQ/game-1.png",
        "https://static.gamezop.com/H1WmafkP9JQ/game-2.png",
        "https://static.gamezop.com/H1WmafkP9JQ/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/H1WmafkP9JQ/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/H1WmafkP9JQ/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: [],
    },
    width: 720,
    height: 1280,
    colorMuted: "#4c3c5c",
    colorVibrant: "#342464",
    privateAllowed: false,
    rating: 3.85,
    numberOfRatings: 5,
    gamePlays: 173109629,
    hasIntegratedAds: false,
  },
  {
    code: "Skke0Kr-O4",
    url: "https://peslsv.play.gamezop.com/g/Skke0Kr-O4",
    name: {
      en: "Monsteroid",
    },
    isPortrait: true,
    description: {
      en: "Join this gigantic alien while he goes on a frenzy to smash up cars in this online action game.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/Skke0Kr-O4/cover.jpg",
      brick: "https://static.gamezop.com/Skke0Kr-O4/brick.png",
      thumb: "https://static.gamezop.com/Skke0Kr-O4/thumb.png",
      wall: "https://static.gamezop.com/Skke0Kr-O4/wall.png",
      square: "https://static.gamezop.com/Skke0Kr-O4/square.png",
      screens: [
        "https://static.gamezop.com/Skke0Kr-O4/game-1.png",
        "https://static.gamezop.com/Skke0Kr-O4/game-2.png",
        "https://static.gamezop.com/Skke0Kr-O4/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/Skke0Kr-O4/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/Skke0Kr-O4/brick-tiny.png",
    },
    categories: {
      en: ["Action"],
    },
    tags: {
      en: ["Boys", "Arcade", "Level-based", "Story-based"],
    },
    width: 400,
    height: 600,
    colorMuted: "#3a5c6b",
    colorVibrant: "#682a19",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1113003,
    hasIntegratedAds: false,
  },
  {
    code: "N1sZfO1fWqg",
    url: "https://peslsv.play.gamezop.com/g/N1sZfO1fWqg",
    name: {
      en: "Grumpy Gorilla",
    },
    isPortrait: true,
    description: {
      en: "This beast is addicted to chopping trees. Ensure he's on the right side else he'd bang his head!",
    },
    gamePreviews: {
      en: "https://youtu.be/eQozH2tIwP4",
    },
    assets: {
      cover: "https://static.gamezop.com/N1sZfO1fWqg/cover.jpg",
      brick: "https://static.gamezop.com/N1sZfO1fWqg/brick.png",
      thumb: "https://static.gamezop.com/N1sZfO1fWqg/thumb.png",
      wall: "https://static.gamezop.com/N1sZfO1fWqg/wall.png",
      square: "https://static.gamezop.com/N1sZfO1fWqg/square.png",
      screens: [
        "https://static.gamezop.com/N1sZfO1fWqg/game-1.png",
        "https://static.gamezop.com/N1sZfO1fWqg/game-2.png",
        "https://static.gamezop.com/N1sZfO1fWqg/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/N1sZfO1fWqg/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/N1sZfO1fWqg/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: [
        "Adventure",
        "Boys",
        "Endless",
        "Exclusive",
        "Fun",
        "Animal",
        "Kids",
        "Time Mgmt.",
        "Arcade",
        "HD",
      ],
    },
    width: 338,
    height: 600,
    colorMuted: "#2c533b",
    colorVibrant: "#045c34",
    privateAllowed: true,
    rating: 4.75,
    numberOfRatings: 1,
    gamePlays: 74027660,
    hasIntegratedAds: false,
  },
  {
    code: "NJ3xGOyfb5l",
    url: "https://peslsv.play.gamezop.com/g/NJ3xGOyfb5l",
    name: {
      en: "Tricky Trip",
    },
    isPortrait: true,
    description: {
      en: "Tap to build bridges to get the car moving. But wait! It can't be that simple, can it? Length is key!",
    },
    gamePreviews: {
      en: "https://youtu.be/9aEHWB02cWM",
    },
    assets: {
      cover: "https://static.gamezop.com/NJ3xGOyfb5l/cover.jpg",
      brick: "https://static.gamezop.com/NJ3xGOyfb5l/brick.png",
      thumb: "https://static.gamezop.com/NJ3xGOyfb5l/thumb.png",
      wall: "https://static.gamezop.com/NJ3xGOyfb5l/wall.png",
      square: "https://static.gamezop.com/NJ3xGOyfb5l/square.png",
      screens: [
        "https://static.gamezop.com/NJ3xGOyfb5l/game-1.png",
        "https://static.gamezop.com/NJ3xGOyfb5l/game-2.png",
        "https://static.gamezop.com/NJ3xGOyfb5l/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/NJ3xGOyfb5l/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/NJ3xGOyfb5l/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: [
        "Boys",
        "Endless",
        "Exclusive",
        "Family",
        "Fun",
        "Girls",
        "Physics",
        "Arcade",
        "Cars",
      ],
    },
    width: 338,
    height: 600,
    colorMuted: "#383749",
    colorVibrant: "#2c345c",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 41747251,
    hasIntegratedAds: false,
  },
  {
    code: "r1zCFBZdV",
    url: "https://peslsv.play.gamezop.com/g/r1zCFBZdV",
    name: {
      en: "Defense of Karmax 3",
    },
    isPortrait: false,
    description: {
      en: "In this HTML5 game, Captain Rogers is a hero defending the galaxy against the alien invasion.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/r1zCFBZdV/cover.jpg",
      brick: "https://static.gamezop.com/r1zCFBZdV/brick.png",
      thumb: "https://static.gamezop.com/r1zCFBZdV/thumb.png",
      wall: "https://static.gamezop.com/r1zCFBZdV/wall.png",
      square: "https://static.gamezop.com/r1zCFBZdV/square.png",
      screens: [
        "https://static.gamezop.com/r1zCFBZdV/game-1.png",
        "https://static.gamezop.com/r1zCFBZdV/game-2.png",
        "https://static.gamezop.com/r1zCFBZdV/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/r1zCFBZdV/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/r1zCFBZdV/brick-tiny.png",
    },
    categories: {
      en: ["Action"],
    },
    tags: {
      en: ["Action", "Boys", "Shooting", "Space", "Arcade"],
    },
    width: 800,
    height: 600,
    colorMuted: "#446a69",
    colorVibrant: "#a46306",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 2428187,
    hasIntegratedAds: false,
  },
  {
    code: "S1VZ-LjQUUl",
    url: "https://peslsv.play.gamezop.com/g/S1VZ-LjQUUl",
    name: {
      en: "Fizz Fuss",
    },
    isPortrait: false,
    description: {
      en: "Is bartending on your bucket-list? Now's your chance! Serve your customers well.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/S1VZ-LjQUUl/cover.jpg",
      brick: "https://static.gamezop.com/S1VZ-LjQUUl/brick.png",
      thumb: "https://static.gamezop.com/S1VZ-LjQUUl/thumb.png",
      wall: "https://static.gamezop.com/S1VZ-LjQUUl/wall.png",
      square: "https://static.gamezop.com/S1VZ-LjQUUl/square.png",
      screens: [
        "https://static.gamezop.com/S1VZ-LjQUUl/game-1.png",
        "https://static.gamezop.com/S1VZ-LjQUUl/game-2.png",
        "https://static.gamezop.com/S1VZ-LjQUUl/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/S1VZ-LjQUUl/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/S1VZ-LjQUUl/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: ["Boys", "Food", "Strategy", "Physics", "Level-based"],
    },
    width: 1500,
    height: 640,
    colorMuted: "#5c3634",
    colorVibrant: "#643423",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1386708,
    hasIntegratedAds: false,
  },
  {
    code: "HyIM86VXAe",
    url: "https://peslsv.play.gamezop.com/g/HyIM86VXAe",
    name: {
      en: "Hats Off",
    },
    isPortrait: true,
    description: {
      en: "Flip the players' hats and land them back on their heads. Hat throw shots are fun!",
    },
    gamePreviews: {
      en: "https://youtu.be/YUE_AbKtpB0",
    },
    assets: {
      cover: "https://static.gamezop.com/HyIM86VXAe/cover.jpg",
      brick: "https://static.gamezop.com/HyIM86VXAe/brick.png",
      thumb: "https://static.gamezop.com/HyIM86VXAe/thumb.png",
      wall: "https://static.gamezop.com/HyIM86VXAe/wall.png",
      square: "https://static.gamezop.com/HyIM86VXAe/square.png",
      screens: [
        "https://static.gamezop.com/HyIM86VXAe/game-1.png",
        "https://static.gamezop.com/HyIM86VXAe/game-2.png",
        "https://static.gamezop.com/HyIM86VXAe/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/HyIM86VXAe/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/HyIM86VXAe/brick-tiny.png",
    },
    categories: {
      en: ["Sports & Racing"],
    },
    tags: {
      en: ["Boys", "Endless", "Fun", "Kids", "Physics", "Cute"],
    },
    width: 338,
    height: 600,
    colorMuted: "#64473c",
    colorVibrant: "#04c4dc",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 5798879,
    hasIntegratedAds: false,
  },
  {
    code: "S1JfKuB9nR",
    url: "https://peslsv.play.gamezop.com/g/S1JfKuB9nR",
    name: {
      en: "Foot Chinko",
    },
    isPortrait: true,
    description: {
      en: "This blend of soccer and physics is an absolute delight that features world's top tournaments.",
    },
    gamePreviews: {
      en: "https://youtu.be/oXd7V1z05o8",
    },
    assets: {
      cover: "https://static.gamezop.com/S1JfKuB9nR/cover.jpg",
      brick: "https://static.gamezop.com/S1JfKuB9nR/brick.png",
      thumb: "https://static.gamezop.com/S1JfKuB9nR/thumb.png",
      wall: "https://static.gamezop.com/S1JfKuB9nR/wall.png",
      square: "https://static.gamezop.com/S1JfKuB9nR/square.png",
      screens: [
        "https://static.gamezop.com/S1JfKuB9nR/game-1.png",
        "https://static.gamezop.com/S1JfKuB9nR/game-2.png",
        "https://static.gamezop.com/S1JfKuB9nR/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/S1JfKuB9nR/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/S1JfKuB9nR/brick-tiny.png",
    },
    categories: {
      en: ["Sports & Racing"],
    },
    tags: {
      en: ["Boys", "Soccer", "Fun", "Sports", "Level-based", "HD", "Cute"],
    },
    width: 768,
    height: 1024,
    colorMuted: "#576432",
    colorVibrant: "#226719",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 10093275,
    hasIntegratedAds: false,
  },
  {
    code: "Bypb6MJvqJQ",
    url: "https://peslsv.play.gamezop.com/g/Bypb6MJvqJQ",
    name: {
      en: "Omit Orange 2",
    },
    isPortrait: true,
    description: {
      en: "Pop the oranges out of the screen while saving the green. Seems easy? Most people can't reach Level 6.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/Bypb6MJvqJQ/cover.jpg",
      brick: "https://static.gamezop.com/Bypb6MJvqJQ/brick.png",
      thumb: "https://static.gamezop.com/Bypb6MJvqJQ/thumb.png",
      wall: "https://static.gamezop.com/Bypb6MJvqJQ/wall.png",
      square: "https://static.gamezop.com/Bypb6MJvqJQ/square.png",
      screens: [
        "https://static.gamezop.com/Bypb6MJvqJQ/game-1.png",
        "https://static.gamezop.com/Bypb6MJvqJQ/game-2.png",
        "https://static.gamezop.com/Bypb6MJvqJQ/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/Bypb6MJvqJQ/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/Bypb6MJvqJQ/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: ["Fun", "Kids", "Strategy", "Physics", "Arcade", "Level-based"],
    },
    width: 480,
    height: 854,
    colorMuted: "#373537",
    colorVibrant: "#ae380d",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1193693,
    hasIntegratedAds: false,
  },
  {
    code: "SyIZjp3GulZ",
    url: "https://peslsv.play.gamezop.com/g/SyIZjp3GulZ",
    name: {
      en: "Black Jack Grid",
    },
    isPortrait: true,
    description: {
      en: "Here's Black Jack with a puzzling twist. Arrange cards horizontally and vertically to bring their sum to 21!",
    },
    gamePreviews: {
      en: "https://youtu.be/vTBFDmqsglo",
    },
    assets: {
      cover: "https://static.gamezop.com/SyIZjp3GulZ/cover.jpg",
      brick: "https://static.gamezop.com/SyIZjp3GulZ/brick.png",
      thumb: "https://static.gamezop.com/SyIZjp3GulZ/thumb.png",
      wall: "https://static.gamezop.com/SyIZjp3GulZ/wall.png",
      square: "https://static.gamezop.com/SyIZjp3GulZ/square.png",
      screens: [
        "https://static.gamezop.com/SyIZjp3GulZ/game-1.png",
        "https://static.gamezop.com/SyIZjp3GulZ/game-2.png",
        "https://static.gamezop.com/SyIZjp3GulZ/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/SyIZjp3GulZ/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/SyIZjp3GulZ/brick-tiny.png",
    },
    categories: {
      en: ["Puzzle & Logic"],
    },
    tags: {
      en: ["Board", "Logic", "Cards", "Strategy", "Puzzle", "Casino"],
    },
    width: 640,
    height: 1136,
    colorMuted: "#312f50",
    colorVibrant: "#6b1919",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1292905,
    hasIntegratedAds: false,
  },
  {
    code: "SkGIa4X0l",
    url: "https://peslsv.play.gamezop.com/g/SkGIa4X0l",
    name: {
      en: "Pai Gow Poker",
    },
    isPortrait: false,
    description: {
      en: "The best Pai Gow Poker online! Bring out your high hands and low hands, and beat the dealer.",
    },
    gamePreviews: {
      en: "https://youtu.be/KsjB4QHTB4Q",
    },
    assets: {
      cover: "https://static.gamezop.com/SkGIa4X0l/cover.jpg",
      brick: "https://static.gamezop.com/SkGIa4X0l/brick.png",
      thumb: "https://static.gamezop.com/SkGIa4X0l/thumb.png",
      wall: "https://static.gamezop.com/SkGIa4X0l/wall.png",
      square: "https://static.gamezop.com/SkGIa4X0l/square.png",
      screens: [
        "https://static.gamezop.com/SkGIa4X0l/game-1.png",
        "https://static.gamezop.com/SkGIa4X0l/game-2.png",
        "https://static.gamezop.com/SkGIa4X0l/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/SkGIa4X0l/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/SkGIa4X0l/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: ["Cards", "Endless", "Strategy", "Casino"],
    },
    width: 1133,
    height: 512,
    colorMuted: "#437945",
    colorVibrant: "#1c6c3d",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 786376,
    hasIntegratedAds: false,
  },
  {
    code: "BJm9VfCmp",
    url: "https://peslsv.play.gamezop.com/g/BJm9VfCmp",
    name: {
      en: "Watch The Walls",
    },
    isPortrait: true,
    description: {
      en: "Little bee needs your help in avoiding the spikes as she makes her way inside a massive beehive.",
    },
    gamePreviews: {
      en: "https://youtu.be/KX5mVZj3Nrs",
    },
    assets: {
      cover: "https://static.gamezop.com/BJm9VfCmp/cover.jpg",
      brick: "https://static.gamezop.com/BJm9VfCmp/brick.png",
      thumb: "https://static.gamezop.com/BJm9VfCmp/thumb.png",
      wall: "https://static.gamezop.com/BJm9VfCmp/wall.png",
      square: "https://static.gamezop.com/BJm9VfCmp/square.png",
      screens: [
        "https://static.gamezop.com/BJm9VfCmp/game-1.png",
        "https://static.gamezop.com/BJm9VfCmp/game-2.png",
        "https://static.gamezop.com/BJm9VfCmp/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/BJm9VfCmp/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/BJm9VfCmp/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: ["Endless", "Animal", "Arcade", "Minimal", "HD"],
    },
    width: 640,
    height: 1136,
    colorMuted: "#50442d",
    colorVibrant: "#9e742f",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 4687514,
    hasIntegratedAds: false,
  },
  {
    code: "S1Clo6hMdeb",
    url: "https://peslsv.play.gamezop.com/g/S1Clo6hMdeb",
    name: {
      en: "Jumpy Ape Joe",
    },
    isPortrait: false,
    description: {
      en: "Help Joe eat up all the bananas! Don't forget to keep an eye out for that ticking timer.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/S1Clo6hMdeb/cover.jpg",
      brick: "https://static.gamezop.com/S1Clo6hMdeb/brick.png",
      thumb: "https://static.gamezop.com/S1Clo6hMdeb/thumb.png",
      wall: "https://static.gamezop.com/S1Clo6hMdeb/wall.png",
      square: "https://static.gamezop.com/S1Clo6hMdeb/square.png",
      screens: [
        "https://static.gamezop.com/S1Clo6hMdeb/game-1.png",
        "https://static.gamezop.com/S1Clo6hMdeb/game-2.png",
        "https://static.gamezop.com/S1Clo6hMdeb/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/S1Clo6hMdeb/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/S1Clo6hMdeb/brick-tiny.png",
    },
    categories: {
      en: ["Adventure"],
    },
    tags: {
      en: [
        "Adventure",
        "Food",
        "Fun",
        "Animal",
        "Kids",
        "Physics",
        "Arcade",
        "Level-based",
      ],
    },
    width: 854,
    height: 480,
    colorMuted: "#322840",
    colorVibrant: "#9a4805",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 3691326,
    hasIntegratedAds: false,
  },
  {
    code: "EJoezu1MWqg",
    url: "https://peslsv.play.gamezop.com/g/EJoezu1MWqg",
    name: {
      en: "Rock the Dock",
    },
    isPortrait: true,
    description: {
      en: "Stack the containers on the ship to accommodate most number of containers; try being perfect.",
    },
    gamePreviews: {
      en: "https://youtu.be/YiCevjMUitI",
    },
    assets: {
      cover: "https://static.gamezop.com/EJoezu1MWqg/cover.jpg",
      brick: "https://static.gamezop.com/EJoezu1MWqg/brick.png",
      thumb: "https://static.gamezop.com/EJoezu1MWqg/thumb.png",
      wall: "https://static.gamezop.com/EJoezu1MWqg/wall.png",
      square: "https://static.gamezop.com/EJoezu1MWqg/square.png",
      screens: [
        "https://static.gamezop.com/EJoezu1MWqg/game-1.png",
        "https://static.gamezop.com/EJoezu1MWqg/game-2.png",
        "https://static.gamezop.com/EJoezu1MWqg/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/EJoezu1MWqg/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/EJoezu1MWqg/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: ["Endless", "Exclusive", "Fun", "Kids", "Arcade", "HD"],
    },
    width: 338,
    height: 600,
    colorMuted: "#434c4d",
    colorVibrant: "#047ca4",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 14278512,
    hasIntegratedAds: false,
  },
  {
    code: "SJXVafJP51Q",
    url: "https://peslsv.play.gamezop.com/g/SJXVafJP51Q",
    name: {
      en: "Nosedive",
    },
    isPortrait: true,
    description: {
      en: "They say death is inevitable. But isn't it all about how long you can survive? You are in a plane crashing towards land - survive as long as you can.",
    },
    gamePreviews: {
      en: "https://youtu.be/CkPjEy8HHek",
    },
    assets: {
      cover: "https://static.gamezop.com/SJXVafJP51Q/cover.jpg",
      brick: "https://static.gamezop.com/SJXVafJP51Q/brick.png",
      thumb: "https://static.gamezop.com/SJXVafJP51Q/thumb.png",
      wall: "https://static.gamezop.com/SJXVafJP51Q/wall.png",
      square: "https://static.gamezop.com/SJXVafJP51Q/square.png",
      screens: [
        "https://static.gamezop.com/SJXVafJP51Q/game-1.png",
        "https://static.gamezop.com/SJXVafJP51Q/game-2.png",
        "https://static.gamezop.com/SJXVafJP51Q/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/SJXVafJP51Q/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/SJXVafJP51Q/brick-tiny.png",
    },
    categories: {
      en: ["Adventure"],
    },
    tags: {
      en: [],
    },
    width: 720,
    height: 1280,
    colorMuted: "#51306e",
    colorVibrant: "#141c5c",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 7945140,
    hasIntegratedAds: false,
  },
  {
    code: "SJcRYSbu4",
    url: "https://peslsv.play.gamezop.com/g/SJcRYSbu4",
    name: {
      en: "Jelly Bears",
    },
    isPortrait: false,
    description: {
      en: "Match bears of the same color to clear the level. P.S. Don't play this game when you are hungry.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/SJcRYSbu4/cover.jpg",
      brick: "https://static.gamezop.com/SJcRYSbu4/brick.png",
      thumb: "https://static.gamezop.com/SJcRYSbu4/thumb.png",
      wall: "https://static.gamezop.com/SJcRYSbu4/wall.png",
      square: "https://static.gamezop.com/SJcRYSbu4/square.png",
      screens: [
        "https://static.gamezop.com/SJcRYSbu4/game-1.png",
        "https://static.gamezop.com/SJcRYSbu4/game-2.png",
        "https://static.gamezop.com/SJcRYSbu4/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/SJcRYSbu4/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/SJcRYSbu4/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: [
        "Family",
        "Fun",
        "Girls",
        "Kids",
        "Match-3",
        "Arcade",
        "Level-based",
      ],
    },
    width: 800,
    height: 600,
    colorMuted: "#663664",
    colorVibrant: "#157511",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1482416,
    hasIntegratedAds: false,
  },
  {
    code: "r1ozpMkD5Jm",
    url: "https://peslsv.play.gamezop.com/g/r1ozpMkD5Jm",
    name: {
      en: "Kickin It",
    },
    isPortrait: true,
    description: {
      en: "Kick it left, kick it right. Kick where you want, just don't let the ball hit the ground, alright?",
    },
    gamePreviews: {
      en: "https://youtu.be/Nq4atBJOWo4",
    },
    assets: {
      cover: "https://static.gamezop.com/r1ozpMkD5Jm/cover.jpg",
      brick: "https://static.gamezop.com/r1ozpMkD5Jm/brick.png",
      thumb: "https://static.gamezop.com/r1ozpMkD5Jm/thumb.png",
      wall: "https://static.gamezop.com/r1ozpMkD5Jm/wall.png",
      square: "https://static.gamezop.com/r1ozpMkD5Jm/square.png",
      screens: [
        "https://static.gamezop.com/r1ozpMkD5Jm/game-1.png",
        "https://static.gamezop.com/r1ozpMkD5Jm/game-2.png",
        "https://static.gamezop.com/r1ozpMkD5Jm/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/r1ozpMkD5Jm/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/r1ozpMkD5Jm/brick-tiny.png",
    },
    categories: {
      en: ["Sports & Racing"],
    },
    tags: {
      en: [],
    },
    width: 480,
    height: 720,
    colorMuted: "#5c4131",
    colorVibrant: "#045c74",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 6758470,
    hasIntegratedAds: false,
  },
  {
    code: "HJee0YHZ_E",
    url: "https://peslsv.play.gamezop.com/g/HJee0YHZ_E",
    name: {
      en: "Penguin Skip",
    },
    isPortrait: false,
    description: {
      en: "Collect as may fish as possible but avoid falling in the icy cold water. Hop your way to endless fun.",
    },
    gamePreviews: {
      en: "https://youtu.be/Rq92ax8Ib4Q",
    },
    assets: {
      cover: "https://static.gamezop.com/HJee0YHZ_E/cover.jpg",
      brick: "https://static.gamezop.com/HJee0YHZ_E/brick.png",
      thumb: "https://static.gamezop.com/HJee0YHZ_E/thumb.png",
      wall: "https://static.gamezop.com/HJee0YHZ_E/wall.png",
      square: "https://static.gamezop.com/HJee0YHZ_E/square.png",
      screens: [
        "https://static.gamezop.com/HJee0YHZ_E/game-1.png",
        "https://static.gamezop.com/HJee0YHZ_E/game-2.png",
        "https://static.gamezop.com/HJee0YHZ_E/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/HJee0YHZ_E/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/HJee0YHZ_E/brick-tiny.png",
    },
    categories: {
      en: ["Adventure"],
    },
    tags: {
      en: [
        "Adventure",
        "Endless",
        "Family",
        "Fun",
        "Animal",
        "Girls",
        "Kids",
        "Physics",
        "Arcade",
        "Cute",
      ],
    },
    width: 800,
    height: 600,
    colorMuted: "#22223e",
    colorVibrant: "#0c0ca8",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 12339787,
    hasIntegratedAds: false,
  },
  {
    code: "HycgCtSWuE",
    url: "https://peslsv.play.gamezop.com/g/HycgCtSWuE",
    name: {
      en: "Space Cowboy",
    },
    isPortrait: false,
    description: {
      en: "This cowboy from Texas has been thrown into space. Good luck helping him gather the cattle!",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/HycgCtSWuE/cover.jpg",
      brick: "https://static.gamezop.com/HycgCtSWuE/brick.png",
      thumb: "https://static.gamezop.com/HycgCtSWuE/thumb.png",
      wall: "https://static.gamezop.com/HycgCtSWuE/wall.png",
      square: "https://static.gamezop.com/HycgCtSWuE/square.png",
      screens: [
        "https://static.gamezop.com/HycgCtSWuE/game-1.png",
        "https://static.gamezop.com/HycgCtSWuE/game-2.png",
        "https://static.gamezop.com/HycgCtSWuE/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/HycgCtSWuE/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/HycgCtSWuE/brick-tiny.png",
    },
    categories: {
      en: ["Adventure"],
    },
    tags: {
      en: ["Adventure", "Endless", "Fun", "Animal", "Space"],
    },
    width: 800,
    height: 600,
    colorMuted: "#323774",
    colorVibrant: "#0b3071",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 589484,
    hasIntegratedAds: false,
  },
  {
    code: "BkR-TMJP5kQ",
    url: "https://peslsv.play.gamezop.com/g/BkR-TMJP5kQ",
    name: {
      en: "Feed The Figures 2",
    },
    isPortrait: true,
    description: {
      en: "Just feed the shapes and stay alive. Most people can't reach level 7 in this puzzle game!",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/BkR-TMJP5kQ/cover.jpg",
      brick: "https://static.gamezop.com/BkR-TMJP5kQ/brick.png",
      thumb: "https://static.gamezop.com/BkR-TMJP5kQ/thumb.png",
      wall: "https://static.gamezop.com/BkR-TMJP5kQ/wall.png",
      square: "https://static.gamezop.com/BkR-TMJP5kQ/square.png",
      screens: [
        "https://static.gamezop.com/BkR-TMJP5kQ/game-1.png",
        "https://static.gamezop.com/BkR-TMJP5kQ/game-2.png",
        "https://static.gamezop.com/BkR-TMJP5kQ/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/BkR-TMJP5kQ/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/BkR-TMJP5kQ/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: ["Logic", "Food", "Fun", "Kids", "Strategy", "Physics", "Cute"],
    },
    width: 480,
    height: 854,
    colorMuted: "#955e03",
    colorVibrant: "#976004",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1918951,
    hasIntegratedAds: false,
  },
  {
    code: "BydCYS-ON",
    url: "https://peslsv.play.gamezop.com/g/BydCYS-ON",
    name: {
      en: "Greedy Gnomes",
    },
    isPortrait: false,
    description: {
      en: "Your aim is to make a column, row, or diagonal of at least four rubies in this multiplayer game.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/BydCYS-ON/cover.jpg",
      brick: "https://static.gamezop.com/BydCYS-ON/brick.png",
      thumb: "https://static.gamezop.com/BydCYS-ON/thumb.png",
      wall: "https://static.gamezop.com/BydCYS-ON/wall.png",
      square: "https://static.gamezop.com/BydCYS-ON/square.png",
      screens: [
        "https://static.gamezop.com/BydCYS-ON/game-1.png",
        "https://static.gamezop.com/BydCYS-ON/game-2.png",
        "https://static.gamezop.com/BydCYS-ON/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/BydCYS-ON/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/BydCYS-ON/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: [
        "Board",
        "Logic",
        "Family",
        "Fun",
        "Strategy",
        "Match-3",
        "Multi-player",
        "Zombie",
        "Puzzle",
      ],
    },
    width: 800,
    height: 600,
    colorMuted: "#5d3563",
    colorVibrant: "#0f5b38",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 433042,
    hasIntegratedAds: false,
  },
  {
    code: "S1-bxXI39",
    url: "https://peslsv.play.gamezop.com/g/S1-bxXI39",
    name: {
      en: "Monsterjong",
    },
    isPortrait: true,
    description: {
      en: "Eliminate all pieces of monsters from the board in this solitaire game, Monsterjong.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/S1-bxXI39/cover.jpg",
      brick: "https://static.gamezop.com/S1-bxXI39/brick.png",
      thumb: "https://static.gamezop.com/S1-bxXI39/thumb.png",
      wall: "https://static.gamezop.com/S1-bxXI39/wall.png",
      square: "https://static.gamezop.com/S1-bxXI39/square.png",
      screens: [
        "https://static.gamezop.com/S1-bxXI39/game-1.png",
        "https://static.gamezop.com/S1-bxXI39/game-2.png",
        "https://static.gamezop.com/S1-bxXI39/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/S1-bxXI39/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/S1-bxXI39/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: [
        "Board",
        "Logic",
        "Cards",
        "Classics",
        "Family",
        "Strategy",
        "Time Mgmt.",
        "Zombie",
        "Level-based",
        "Puzzle",
      ],
    },
    width: 525,
    height: 600,
    colorMuted: "#70463a",
    colorVibrant: "#698315",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 1874468,
    hasIntegratedAds: false,
  },
  {
    code: "rkYbNLTIT-x",
    url: "https://peslsv.play.gamezop.com/g/rkYbNLTIT-x",
    name: {
      en: "Knight Ride",
    },
    isPortrait: false,
    description: {
      en: "The canon's loaded and the knight's ready! Bounce through your flight while avoiding the onslaught of monsters.",
    },
    gamePreviews: {
      en: "https://youtu.be/hIVrutv2gvM",
    },
    assets: {
      cover: "https://static.gamezop.com/rkYbNLTIT-x/cover.jpg",
      brick: "https://static.gamezop.com/rkYbNLTIT-x/brick.png",
      thumb: "https://static.gamezop.com/rkYbNLTIT-x/thumb.png",
      wall: "https://static.gamezop.com/rkYbNLTIT-x/wall.png",
      square: "https://static.gamezop.com/rkYbNLTIT-x/square.png",
      screens: [
        "https://static.gamezop.com/rkYbNLTIT-x/game-1.png",
        "https://static.gamezop.com/rkYbNLTIT-x/game-2.png",
        "https://static.gamezop.com/rkYbNLTIT-x/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/rkYbNLTIT-x/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/rkYbNLTIT-x/brick-tiny.png",
    },
    categories: {
      en: ["Adventure"],
    },
    tags: {
      en: ["Adventure", "Endless", "Kids", "Physics", "Arcade"],
    },
    width: 800,
    height: 450,
    colorMuted: "#543a32",
    colorVibrant: "#bb2137",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 17644988,
    hasIntegratedAds: false,
  },
  {
    code: "4y6efOyf-5g",
    url: "https://peslsv.play.gamezop.com/g/4y6efOyf-5g",
    name: {
      en: "Bouncing Beasts",
    },
    isPortrait: true,
    description: {
      en: "Help the animals hop from one twig to the other, without letting the rings touch the wood!",
    },
    gamePreviews: {
      en: "https://youtu.be/043jC1nLJ64",
    },
    assets: {
      cover: "https://static.gamezop.com/4y6efOyf-5g/cover.jpg",
      brick: "https://static.gamezop.com/4y6efOyf-5g/brick.png",
      thumb: "https://static.gamezop.com/4y6efOyf-5g/thumb.png",
      wall: "https://static.gamezop.com/4y6efOyf-5g/wall.png",
      square: "https://static.gamezop.com/4y6efOyf-5g/square.png",
      screens: [
        "https://static.gamezop.com/4y6efOyf-5g/game-1.png",
        "https://static.gamezop.com/4y6efOyf-5g/game-2.png",
        "https://static.gamezop.com/4y6efOyf-5g/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/4y6efOyf-5g/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/4y6efOyf-5g/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: [
        "Adventure",
        "Endless",
        "Exclusive",
        "Fun",
        "Animal",
        "Kids",
        "Arcade",
        "Cute",
      ],
    },
    width: 400,
    height: 600,
    colorMuted: "#5c3c2c",
    colorVibrant: "#946418",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 41720329,
    hasIntegratedAds: false,
  },
  {
    code: "VJOGOyGb9l",
    url: "https://peslsv.play.gamezop.com/g/VJOGOyGb9l",
    name: {
      en: "Flying School",
    },
    isPortrait: false,
    description: {
      en: "Help cute birds learn to fly. Drag and aim to make them fly from one nest to the other.",
    },
    gamePreviews: {
      en: "https://youtu.be/TJb2aW6dUGw",
    },
    assets: {
      cover: "https://static.gamezop.com/VJOGOyGb9l/cover.jpg",
      brick: "https://static.gamezop.com/VJOGOyGb9l/brick.png",
      thumb: "https://static.gamezop.com/VJOGOyGb9l/thumb.png",
      wall: "https://static.gamezop.com/VJOGOyGb9l/wall.png",
      square: "https://static.gamezop.com/VJOGOyGb9l/square.png",
      screens: [
        "https://static.gamezop.com/VJOGOyGb9l/game-1.png",
        "https://static.gamezop.com/VJOGOyGb9l/game-2.png",
        "https://static.gamezop.com/VJOGOyGb9l/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/VJOGOyGb9l/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/VJOGOyGb9l/brick-tiny.png",
    },
    categories: {
      en: ["Adventure"],
    },
    tags: {
      en: [
        "Adventure",
        "Logic",
        "Family",
        "Fun",
        "Animal",
        "Girls",
        "Kids",
        "Level-based",
        "HD",
        "Cute",
      ],
    },
    width: 800,
    height: 600,
    colorMuted: "#371d1d",
    colorVibrant: "#481b5f",
    privateAllowed: true,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 8010900,
    hasIntegratedAds: false,
  },
  {
    code: "S14VrK8B",
    url: "https://peslsv.play.gamezop.com/g/S14VrK8B",
    name: {
      en: "Pixel Zombies",
    },
    isPortrait: true,
    description: {
      en: "The zombie invasion just hit London. Smash every zombie but don't kill civilians in this zombie game.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/S14VrK8B/cover.jpg",
      brick: "https://static.gamezop.com/S14VrK8B/brick.png",
      thumb: "https://static.gamezop.com/S14VrK8B/thumb.png",
      wall: "https://static.gamezop.com/S14VrK8B/wall.png",
      square: "https://static.gamezop.com/S14VrK8B/square.png",
      screens: [
        "https://static.gamezop.com/S14VrK8B/game-1.png",
        "https://static.gamezop.com/S14VrK8B/game-2.png",
        "https://static.gamezop.com/S14VrK8B/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/S14VrK8B/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/S14VrK8B/brick-tiny.png",
    },
    categories: {
      en: ["Action"],
    },
    tags: {
      en: [
        "Action",
        "Boys",
        "Shooting",
        "Strategy",
        "Pixel",
        "Zombie",
        "Level-based",
      ],
    },
    width: 338,
    height: 600,
    colorMuted: "#534431",
    colorVibrant: "#6e2214",
    privateAllowed: false,
    rating: 3.75,
    numberOfRatings: 0,
    gamePlays: 3117341,
    hasIntegratedAds: false,
  },
  {
    code: "rkWfy2pXq0r",
    url: "https://peslsv.play.gamezop.com/g/rkWfy2pXq0r",
    name: {
      en: "Fruit Chop",
    },
    isPortrait: false,
    description: {
      en: "Swipe the screen to chop fruits but don't hit the bombs! So unsheathe your sword and get ready to play the most fun fruit slice game online.",
    },
    gamePreviews: {
      en: "",
    },
    assets: {
      cover: "https://static.gamezop.com/rkWfy2pXq0r/cover.jpg",
      brick: "https://static.gamezop.com/rkWfy2pXq0r/brick.png",
      thumb: "https://static.gamezop.com/rkWfy2pXq0r/thumb.png",
      wall: "https://static.gamezop.com/rkWfy2pXq0r/wall.png",
      square: "https://static.gamezop.com/rkWfy2pXq0r/square.png",
      screens: [
        "https://static.gamezop.com/rkWfy2pXq0r/game-1.png",
        "https://static.gamezop.com/rkWfy2pXq0r/game-2.png",
        "https://static.gamezop.com/rkWfy2pXq0r/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/rkWfy2pXq0r/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/rkWfy2pXq0r/brick-tiny.png",
    },
    categories: {
      en: ["Arcade"],
    },
    tags: {
      en: [],
    },
    width: 640,
    height: 360,
    colorMuted: "#2F0743",
    colorVibrant: "#41295A",
    privateAllowed: true,
    rating: 4,
    numberOfRatings: 1,
    gamePlays: 66031607,
    hasIntegratedAds: false,
  },
  {
    code: "SykGDfUKOkg",
    url: "https://peslsv.play.gamezop.com/g/SykGDfUKOkg",
    name: {
      en: "Traffic Command",
    },
    isPortrait: true,
    description: {
      en: "The city crossing sees some insane traffic. Navigate the cars carefully without letting any crash.",
    },
    gamePreviews: {
      en: "https://youtu.be/oE50QlNR4iM",
    },
    assets: {
      cover: "https://static.gamezop.com/SykGDfUKOkg/cover.jpg",
      brick: "https://static.gamezop.com/SykGDfUKOkg/brick.png",
      thumb: "https://static.gamezop.com/SykGDfUKOkg/thumb.png",
      wall: "https://static.gamezop.com/SykGDfUKOkg/wall.png",
      square: "https://static.gamezop.com/SykGDfUKOkg/square.png",
      screens: [
        "https://static.gamezop.com/SykGDfUKOkg/game-1.png",
        "https://static.gamezop.com/SykGDfUKOkg/game-2.png",
        "https://static.gamezop.com/SykGDfUKOkg/game-3.png",
      ],
      coverTiny: "https://static.gamezop.com/SykGDfUKOkg/cover-tiny.jpg",
      brickTiny: "https://static.gamezop.com/SykGDfUKOkg/brick-tiny.png",
    },
    categories: {
      en: ["Strategy"],
    },
    tags: {
      en: ["Boys", "Endless", "Kids", "Physics", "Arcade", "Cars"],
    },
    width: 338,
    height: 600,
    colorMuted: "#545463",
    colorVibrant: "#7c1709",
    privateAllowed: true,
    rating: 4.08,
    numberOfRatings: 3,
    gamePlays: 16647427,
    hasIntegratedAds: false,
  },
];
